WebDevProject/Ten/GameGuides/urls.py
from django.urls import path
from GameGuides import views

app_name = 'gameguides'

urlpatterns = [
    path('', views.gameguides_home_view, name='game_guides_home'),
    path('hsr_banner_history/', views.hsr_banner_history_view, name='hsr_banner_history'),
    path('survivorio_clans/', views.survivorio_clans_view, name='survivorio_clans'),
    path('survivorio_gear/', views.survivorio_gear_view, name='survivorio_gear'),
    path('survivorio_maps/', views.survivorio_map_types_bosses_view, name='survivorio_maps'),
    path('survivorio_pets/', views.survivorio_pets_view, name='survivorio_pets'),
    path('survivorio_survivors/', views.survivorio_survivors_view, name='survivorio_survivors'),
    path('survivorio_merging/', views.survivorio_merging_view, name='survivorio_merging'),
]

WebDevProject/Ten/StockTracker/urls.py
from django.urls import path
from StockTracker import views

app_name = 'stockapp'

urlpatterns = [
    path('', views.stock_app_home_view, name='stock_app_home'),
    path('stock_history', views.stock_historical_visualizer_view, name='stock_history'),
]

WebDevProject/Ten/Ten/urls.py
from django.contrib import admin
from django.urls import path, include
from Ten import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('resume/', views.resume_view, name='resume'),
    path('language_guides/', include('TenAppOne.urls')),
    path('user_auth/', include('UserAuthentication.urls')),
    path('game_guides/', include('GameGuides.urls')),
    path('stock_app/', include('StockTracker.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

WebDevProject/Ten/TenAppOne/urls.py
from django.urls import path
from TenAppOne import views

app_name = 'tenappone'

urlpatterns = [
    path('', views.language_guides_home_view, name='language_guides_home'),

    path('html_basics/', views.html_basics_view, name='html_basics'),
    path('html_elements_reference/', views.html_elements_reference_view, name='html_elements_reference'),

    path('css_basics/', views.css_basics_view, name='css_basics'),
    path('css_layouts/', views.css_layouts_view, name='css_layouts'),
    path('css_selectors/', views.css_selectors_view, name='css_selectors'),

    path('bootstrap_forms/', views.bootstrap_forms_view, name='bootstrap_forms'),
    path('bootstrap_components/', views.bootstrap_components_view, name='bootstrap_components'),
    path('bootstrap_styling/', views.bootstrap_styling_view, name='bootstrap_styling'),

    path('javascript_basics/', views.javascript_basics_view, name='javascript_basics'),
    path('dom_basics/', views.dom_basics_view, name='dom_basics'),
    path('jquery_basics/', views.jquery_basics_view, name='jquery_basics'),
    path('dom_reference/', views.dom_reference_view, name='dom_reference'),
    path('dom_events_reference/', views.dom_events_reference_view, name='dom_events_reference'),

    path('django_setup/', views.django_setup_view, name='django_setup'),
    path('django_views_and_urls/', views.django_views_and_urls_view, name='django_views_and_urls'),
    path('django_templates/', views.django_templates_view, name='django_templates'),
    path('django_static_files/', views.django_static_files_view, name='django_static_files'),
    path('django_models/', views.django_models_view, name='django_models'),
    path('django_admin_interface/', views.django_admin_interface_view, name='django_admin_interface'),
    path('django_creating_sample_data/', views.django_creating_sample_data_view, name='django_creating_sample_data'),
    path('django_model_queries/', views.django_model_queries_view, name='django_model_queries'),
    path('django_mtv_paradigm/', views.django_mtv_paradigm_view, name='django_mtv_paradigm'),
    path('django_forms/', views.django_forms_view, name='django_forms'),
    path('django_form_validation/', views.django_form_validation_view, name='django_form_validation'),
    path('django_model_forms/', views.django_model_forms_view, name='django_model_forms'),
    path('django_relative_urls/', views.django_relative_urls_view, name='django_relative_urls'),
    path('django_users/', views.django_users_view, name='django_users'),
    path('django_user_login_logout/', views.django_user_login_logout_view, name='django_user_login_logout'),
    path('django_encryption_and_validation/', views.django_ecryption_and_validation_view,
         name='django_encryption_and_validation'),
    path('django_deployment/', views.django_deployment_view, name='django_deployment'),
    path('django_cbvs/', views.django_cbvs_view, name='django_cbvs'),

    path('git_basics/', views.git_basics_view, name='git_basics'),
    path('git_advanced/', views.git_advanced_view, name='git_advanced'),

    path('python/', views.python_view, name='python'),

    path('sql_basics/', views.sql_basics_view, name='sql_basics'),

    path('vim_basics/', views.vim_basics_view, name='vim_basics'),

    path('regex_reference/', views.regex_reference_view, name='regex_reference'),

    path('interview_prep/', views.interview_prep_view, name='interview_prep'),

    path('nodejs_intro_install/', views.nodejs_intro_and_install, name='nodejs_intro_and_install'),
    # path('nodejs_global_variables/', views.nodejs_global_variables, name='nodejs_global_variabls'),
    path('nodejs_express/', views.nodejs_express, name='nodejs_express'),

    path('react_basics/', views.react_basics, name='react_basics'),
    path('react_and_django/', views.react_and_django, name='react_and_django'),
    path('react_examples/', views.react_examples, name='react_examples'),

    path('typescript_intro/', views.typescript_intro, name='typescript_intro'),

    path('typescript_reference/', views.typescript_reference, name='typescript_reference'),
]

WebDevProject/Ten/templates/home_page/home.html
{% extends 'base_template_home.html' %}

{% load static %}

{% block head_block %}
    <link rel="stylesheet" href="{% static 'css/global_styling.css' %}">
    <link rel="stylesheet" href="{% static 'css/card_styling.css' %}">
    <link rel="stylesheet" href="{% static 'css/effects_styling.css' %}">
    <title>Metacrypha</title>
{% endblock %}

{% block body_block %}
    <!--<h1 class="text-center mb-4"><strong>Welcome to the &rppolint;<span class="door">&rpargt;</span>&rnmid;&rtrif;</strong></h1>-->
    <div class="bg-body-tertiary rounded-3 p-5 mb-4 ">
        <div class="container-fluid py-5">
            <h1 class="display-4 fw-bold">
                {#            <strong>Welcome to the &rppolint;<span class="door">&rpargt;</span>&rnmid;&rtrif;</strong>#}
                <strong>Welcome to the <span class="key">Metacrypha</span>.</strong>
            </h1>
            <p class="col-mb-8 fs-4">
                Here you'll find guides for a variety of topics. If you're looking to read up and potentially add some
                new coding skills to your portfolio, check out the <a href="{% url 'tenappone:language_guides_home' %}">
                Coders' Corner</a>. Looking to gain some insight into the stock market? Try out the stock history
                tracker
                tool in the <a href="{% url 'stockapp:stock_history' %}">Stockbrocker's Study</a>. If you're looking for
                some game guides and references, head over to the <a href="{% url 'gameguides:game_guides_home' %}">Gamers'
                Grove</a>.
            </p>
            <hr>
            <p class="col-mb-8 fs-5">
                Please click below if you would like to know about the developer.
            </p>
            <a class="btn btn-danger btn-lg" role="button" href="{% url 'about' %}">About</a>
        </div>
    </div>
    <div>
        <div class="row">
            <div class="col-4">
                <div class="card h-100">
                    <a href="{% url 'tenappone:language_guides_home' %}">
                        <div class="card-body">
                            <h4 class="card-title">Coders' Corner</h4>
                            <p class="card-text">
                                Click here to check out some programming languages/framework guides!
                            </p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-4">
                <div class="card h-100">
                    <a href="{% url 'gameguides:game_guides_home' %}">
                        <div class="card-body">
                            <h4 class="card-title">Gamers' Grove</h4>
                            <p class="card-text">
                                Click here to check out some game guides!
                            </p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-4">
                <div class="card h-100">
                    <a href="{% url 'stockapp:stock_app_home' %}">
                        <div class="card-body">
                            <h4 class="card-title">Stockbrokers' Study</h4>
                            <p class="card-text">
                                Click here to check out some stock utilities/tools!
                            </p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

WebDevProject/Ten/templates/home_page/resume.html
{% extends 'base_template_home.html' %}

{% load static %}

{% block head_block %}
<link rel="stylesheet" href="{% static 'css/global_styling.css' %}">
<link rel="stylesheet" href="{% static 'css/effects_styling.css' %}">
<link rel="stylesheet" href="{% static 'css/about.css' %}">
<title>Resume PDF</title>
{% endblock %}

{% block body_block %}
<!--<h1>About Me</h1>-->
<div class="form-control mb-1">
    <h1>Resume PDF</h1>
    <object data="{% static 'media/texts/resume.pdf' %}" type="application/pdf" width="100%" height="2200px;">
        File missing or unsupported.
    </object>
</div>
{% endblock %}

{% block chapter_block %}
{% endblock %}

{% block glossary_block %}
{% endblock %}