WebDevProject/Ten/GameGuides/urls.py
from django.urls import path
from GameGuides import views

app_name = 'gameguides'

urlpatterns = [
    path('', views.gameguides_home_view, name='game_guides_home'),
    path('hsr_banner_history/', views.hsr_banner_history_view, name='hsr_banner_history'),
    path('survivorio_clans/', views.survivorio_clans_view, name='survivorio_clans'),
    path('survivorio_gear/', views.survivorio_gear_view, name='survivorio_gear'),
    path('survivorio_maps/', views.survivorio_map_types_bosses_view, name='survivorio_maps'),
    path('survivorio_pets/', views.survivorio_pets_view, name='survivorio_pets'),
    path('survivorio_survivors/', views.survivorio_survivors_view, name='survivorio_survivors'),
    path('survivorio_merging/', views.survivorio_merging_view, name='survivorio_merging'),
]

WebDevProject/Ten/StockTracker/urls.py
from django.urls import path
from StockTracker import views

app_name = 'stockapp'

urlpatterns = [
    path('', views.stock_app_home_view, name='stock_app_home'),
    path('stock_history', views.stock_historical_visualizer_view, name='stock_history'),
]

WebDevProject/Ten/Ten/urls.py
from django.contrib import admin
from django.urls import path, include
from Ten import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('resume/', views.resume_view, name='resume'),
    path('language_guides/', include('TenAppOne.urls')),
    path('user_auth/', include('UserAuthentication.urls')),
    path('game_guides/', include('GameGuides.urls')),
    path('stock_app/', include('StockTracker.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

WebDevProject/Ten/TenAppOne/urls.py
from django.urls import path
from TenAppOne import views

app_name = 'tenappone'

urlpatterns = [
    path('', views.language_guides_home_view, name='language_guides_home'),

    path('html_basics/', views.html_basics_view, name='html_basics'),
    path('html_elements_reference/', views.html_elements_reference_view, name='html_elements_reference'),

    path('css_basics/', views.css_basics_view, name='css_basics'),
    path('css_layouts/', views.css_layouts_view, name='css_layouts'),
    path('css_selectors/', views.css_selectors_view, name='css_selectors'),

    path('bootstrap_forms/', views.bootstrap_forms_view, name='bootstrap_forms'),
    path('bootstrap_components/', views.bootstrap_components_view, name='bootstrap_components'),
    path('bootstrap_styling/', views.bootstrap_styling_view, name='bootstrap_styling'),

    path('javascript_basics/', views.javascript_basics_view, name='javascript_basics'),
    path('dom_basics/', views.dom_basics_view, name='dom_basics'),
    path('jquery_basics/', views.jquery_basics_view, name='jquery_basics'),
    path('dom_reference/', views.dom_reference_view, name='dom_reference'),
    path('dom_events_reference/', views.dom_events_reference_view, name='dom_events_reference'),

    path('django_setup/', views.django_setup_view, name='django_setup'),
    path('django_views_and_urls/', views.django_views_and_urls_view, name='django_views_and_urls'),
    path('django_templates/', views.django_templates_view, name='django_templates'),
    path('django_static_files/', views.django_static_files_view, name='django_static_files'),
    path('django_models/', views.django_models_view, name='django_models'),
    path('django_admin_interface/', views.django_admin_interface_view, name='django_admin_interface'),
    path('django_creating_sample_data/', views.django_creating_sample_data_view, name='django_creating_sample_data'),
    path('django_model_queries/', views.django_model_queries_view, name='django_model_queries'),
    path('django_mtv_paradigm/', views.django_mtv_paradigm_view, name='django_mtv_paradigm'),
    path('django_forms/', views.django_forms_view, name='django_forms'),
    path('django_form_validation/', views.django_form_validation_view, name='django_form_validation'),
    path('django_model_forms/', views.django_model_forms_view, name='django_model_forms'),
    path('django_relative_urls/', views.django_relative_urls_view, name='django_relative_urls'),
    path('django_users/', views.django_users_view, name='django_users'),
    path('django_user_login_logout/', views.django_user_login_logout_view, name='django_user_login_logout'),
    path('django_encryption_and_validation/', views.django_ecryption_and_validation_view,
         name='django_encryption_and_validation'),
    path('django_deployment/', views.django_deployment_view, name='django_deployment'),
    path('django_cbvs/', views.django_cbvs_view, name='django_cbvs'),

    path('git_basics/', views.git_basics_view, name='git_basics'),
    path('git_advanced/', views.git_advanced_view, name='git_advanced'),

    path('python/', views.python_view, name='python'),

    path('sql_basics/', views.sql_basics_view, name='sql_basics'),

    path('vim_basics/', views.vim_basics_view, name='vim_basics'),

    path('regex_reference/', views.regex_reference_view, name='regex_reference'),

    path('interview_prep/', views.interview_prep_view, name='interview_prep'),

    path('nodejs_intro_install/', views.nodejs_intro_and_install, name='nodejs_intro_and_install'),
    # path('nodejs_global_variables/', views.nodejs_global_variables, name='nodejs_global_variabls'),
    path('nodejs_express/', views.nodejs_express, name='nodejs_express'),

    path('react_basics/', views.react_basics, name='react_basics'),
    path('react_and_django/', views.react_and_django, name='react_and_django'),
    path('react_examples/', views.react_examples, name='react_examples'),

    path('typescript_intro/', views.typescript_intro, name='typescript_intro'),

    path('typescript_reference/', views.typescript_reference, name='typescript_reference'),
]

WebDevProject/Ten/UserAuthentication/urls.py
from django.urls import path
from UserAuthentication import views

app_name = 'user_auth'

urlpatterns = [
    path('registration/', views.registration_view, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user_roster/', views.user_roster_view, name='user_roster')
]

WebDevProject/Ten/templates/base_template_gameguides.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <!--Bootstrap CDN-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <!--JQuery CDN-->
    <script src="https://code.jquery.com/jquery-3.7.1.js"
            integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <!--Favicon-->
    <link rel="icon" href="{% static 'media/images/favicon_16x16.png' %}">
    {% block head_block %}
    {% endblock %}
</head>
<body>
<div class="navbar navbar-expand-lg navbar-dark border-bottom border-light bg-dark fixed-top px-3">
    <!--    <div class="container-fluid">-->
    <a class="navbar-brand text-light" href="{% url 'home' %}">
        <img src="{% static 'media/images/brand_192x192.png' %}" alt="" width="50px">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_one">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapse_one">
        <ul class="navbar-nav navbar-light">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown" href="#">Honkai: Star Rail</a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item" href="{% url 'gameguides:hsr_banner_history' %}">
                            Character/Light Cone Banner History
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown" href="#">Survivor.io</a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item" href="{% url 'gameguides:survivorio_survivors' %}">Survivors</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'gameguides:survivorio_clans' %}">Clan Expeditions</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'gameguides:survivorio_gear' %}">Gear</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'gameguides:survivorio_maps' %}">Maps</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'gameguides:survivorio_pets' %}">Pets</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'gameguides:survivorio_merging' %}">Merging Guide</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <div>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'user_auth:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'user_auth:registration' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'user_auth:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
<!--</div>-->
<div>
    {% block body_block %}
    {% endblock %}
</div>
<br><br>
<div class="navbar navbar-expand-lg navbar-left bg-dark border-top border-light navbar-light fixed-bottom">
    <div class="container-fluid">
        <!--        <a class="navbar-brand text-light" href="#"></a>-->
        <ul class="navbar-nav">
            <!--            <li class="nav-item">-->
            <!--                &lt;!&ndash;                <a class="nav-link text-light" href="#">About</a>&ndash;&gt;-->
            <!--                <a class="nav-link text-light" href="#">-->
            <!--                    <strong>-->
            <!--                    </strong>-->
            <!--                </a>-->
            <!--            </li>-->
            <li class="nav-item dropup">
                <!--'dropup' displays the dropdown menu above rather than below. Other options: dropright, dropleft-->
                <a class="nav-link dropdown-toggle text-light" href="#" data-bs-toggle="dropdown">
                    <strong>
                        {% block chapter_block %}
                        {% endblock %}
                    </strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-scrollbar">
                    {% block glossary_block %}
                    {% endblock %}
                    <!--                    <li>-->
                    <!--                        <a class="dropdown-item" href="#">English</a>-->
                    <!--                    </li>-->
                    <!--                    <li>-->
                    <!--                        <a class="dropdown-item" href="#">Spanish</a>-->
                    <!--                    </li>-->
                    <!--                    <li>-->
                    <!--                        <a class="dropdown-item" href="#">Chinese</a>-->
                    <!--                    </li>-->
                </ul>
            </li>
        </ul>
        <form class="d-flex">
            <div class="input-group">
                <span class="input-group-text bg-dark border border-dark text-light">Search:</span>
                <button type="button" class="btn btn-outline-light border border-dark" hidden="hidden" id="prev_result_button_id">
                    &lt;
                </button>
                <button type="button" class="btn btn-outline-light border border-dark" hidden="hidden" id="next_result_button_id">
                    &gt;
                </button>
                <input type="text" class="form-control" placeholder="Search on page..." id="search_box_id">
            </div>
        </form>
    </div>
</div>
<script src="{% static 'js/search_page_function.js' %}"></script>
</body>
</html>

WebDevProject/Ten/templates/base_template_home.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <!--    &lt;!&ndash;Bootstrap CDN&ndash;&gt;-->
    <!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"-->
    <!--          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">-->
    <!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"-->
    <!--            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"-->
    <!--            crossorigin="anonymous"></script>-->
    <!--    &lt;!&ndash;JQuery CDN&ndash;&gt;-->
    <!--    <script src="https://code.jquery.com/jquery-3.7.1.js"-->
    <!--            integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>-->

    <!--Using a localized version of Bootstrap-->
    <script src="{% static 'dependencies/jquery/jquery-3.7.1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'dependencies/bootstrap/css/bootstrap.css' %}">
    <script rel="stylesheet" src="{% static 'dependencies/bootstrap/js/bootstrap.bundle.js' %}"></script>

    <!--Favicon-->
    <link rel="icon" href="{% static 'media/images/favicon_16x16.png' %}">
    {% block head_block %}
    {% endblock %}
</head>
<body>
<div class="navbar navbar-expand-lg navbar-dark border-bottom border-light bg-dark fixed-top px-3">
    <!--    <div class="container-fluid">-->
    <a class="navbar-brand text-light" href="{% url 'home' %}">
        <img src="{% static 'media/images/brand_192x192.png' %}" alt="" width="50px">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_one">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapse_one">
        <ul class="navbar-nav navbar-light">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown" href="#">Guides</a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item" href="{% url 'tenappone:language_guides_home' %}">
                            Coders' Corner
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'gameguides:game_guides_home' %}">
                            Gamers' Grove
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'stockapp:stock_app_home' %}">
                            Stockbrokers' Study
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'about' %}">About</a>
            </li>
        </ul>
    </div>
    <div>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'user_auth:user_roster' %}">User Registry</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'user_auth:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'user_auth:registration' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'user_auth:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'admin:index' %}">Admin Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
<!--</div>-->
<div>
    {% block body_block %}
    {% endblock %}
</div>
<br><br>
<div class="navbar navbar-expand-lg navbar-left bg-dark border-top border-light navbar-light fixed-bottom">
    <div class="container-fluid">
        <!--        <a class="navbar-brand text-light" href="#"></a>-->
        <ul class="navbar-nav">
            <!--            <li class="nav-item">-->
            <!--                &lt;!&ndash;                <a class="nav-link text-light" href="#">About</a>&ndash;&gt;-->
            <!--                <a class="nav-link text-light" href="#">-->
            <!--                    <strong>-->
            <!--                    </strong>-->
            <!--                </a>-->
            <!--            </li>-->
            <li class="nav-item dropup">
                <!--'dropup' displays the dropdown menu above rather than below. Other options: dropright, dropleft-->
                <a class="nav-link dropdown-toggle text-light" href="#" data-bs-toggle="dropdown">
                    <strong>
                        {% block chapter_block %}
                        {% endblock %}
                    </strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-scrollbar">
                    {% block glossary_block %}
                    {% endblock %}
                    <!--                    <li>-->
                    <!--                        <a class="dropdown-item" href="#">English</a>-->
                    <!--                    </li>-->
                    <!--                    <li>-->
                    <!--                        <a class="dropdown-item" href="#">Spanish</a>-->
                    <!--                    </li>-->
                    <!--                    <li>-->
                    <!--                        <a class="dropdown-item" href="#">Chinese</a>-->
                    <!--                    </li>-->
                </ul>
            </li>
        </ul>
        <form class="d-flex">
            <div class="input-group">
                <span class="input-group-text bg-dark border border-dark text-light">Search:</span>
                <button type="button" class="btn btn-outline-light border border-dark" hidden="hidden" id="prev_result_button_id">
                    &lt;
                </button>
                <button type="button" class="btn btn-outline-light border border-dark" hidden="hidden" id="next_result_button_id">
                    &gt;
                </button>
                <input type="text" class="form-control" placeholder="Search on page..." id="search_box_id">
            </div>
        </form>
    </div>
</div>
<script src="{% static 'js/search_page_function.js' %}"></script>
</body>
</html>