WebDevProject/Ten/Ten/urls.py
from django.contrib import admin
from django.urls import path, include
from Ten import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('resume/', views.resume_view, name='resume'),
    path('language_guides/', include('TenAppOne.urls')),
    path('user_auth/', include('UserAuthentication.urls')),
    path('game_guides/', include('GameGuides.urls')),
    path('stock_app/', include('StockTracker.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

WebDevProject/Ten/TenAppOne/urls.py
from django.urls import path
from TenAppOne import views

app_name = 'tenappone'

urlpatterns = [
    path('', views.language_guides_home_view, name='language_guides_home'),

    path('html_basics/', views.html_basics_view, name='html_basics'),
    path('html_elements_reference/', views.html_elements_reference_view, name='html_elements_reference'),

    path('css_basics/', views.css_basics_view, name='css_basics'),
    path('css_layouts/', views.css_layouts_view, name='css_layouts'),
    path('css_selectors/', views.css_selectors_view, name='css_selectors'),

    path('bootstrap_forms/', views.bootstrap_forms_view, name='bootstrap_forms'),
    path('bootstrap_components/', views.bootstrap_components_view, name='bootstrap_components'),
    path('bootstrap_styling/', views.bootstrap_styling_view, name='bootstrap_styling'),

    path('javascript_basics/', views.javascript_basics_view, name='javascript_basics'),
    path('dom_basics/', views.dom_basics_view, name='dom_basics'),
    path('jquery_basics/', views.jquery_basics_view, name='jquery_basics'),
    path('dom_reference/', views.dom_reference_view, name='dom_reference'),
    path('dom_events_reference/', views.dom_events_reference_view, name='dom_events_reference'),

    path('django_setup/', views.django_setup_view, name='django_setup'),
    path('django_views_and_urls/', views.django_views_and_urls_view, name='django_views_and_urls'),
    path('django_templates/', views.django_templates_view, name='django_templates'),
    path('django_static_files/', views.django_static_files_view, name='django_static_files'),
    path('django_models/', views.django_models_view, name='django_models'),
    path('django_admin_interface/', views.django_admin_interface_view, name='django_admin_interface'),
    path('django_creating_sample_data/', views.django_creating_sample_data_view, name='django_creating_sample_data'),
    path('django_model_queries/', views.django_model_queries_view, name='django_model_queries'),
    path('django_mtv_paradigm/', views.django_mtv_paradigm_view, name='django_mtv_paradigm'),
    path('django_forms/', views.django_forms_view, name='django_forms'),
    path('django_form_validation/', views.django_form_validation_view, name='django_form_validation'),
    path('django_model_forms/', views.django_model_forms_view, name='django_model_forms'),
    path('django_relative_urls/', views.django_relative_urls_view, name='django_relative_urls'),
    path('django_users/', views.django_users_view, name='django_users'),
    path('django_user_login_logout/', views.django_user_login_logout_view, name='django_user_login_logout'),
    path('django_encryption_and_validation/', views.django_ecryption_and_validation_view,
         name='django_encryption_and_validation'),
    path('django_deployment/', views.django_deployment_view, name='django_deployment'),
    path('django_cbvs/', views.django_cbvs_view, name='django_cbvs'),

    path('git_basics/', views.git_basics_view, name='git_basics'),
    path('git_advanced/', views.git_advanced_view, name='git_advanced'),

    path('python/', views.python_view, name='python'),

    path('sql_basics/', views.sql_basics_view, name='sql_basics'),

    path('vim_basics/', views.vim_basics_view, name='vim_basics'),

    path('regex_reference/', views.regex_reference_view, name='regex_reference'),

    path('interview_prep/', views.interview_prep_view, name='interview_prep'),

    path('nodejs_intro_install/', views.nodejs_intro_and_install, name='nodejs_intro_and_install'),
    # path('nodejs_global_variables/', views.nodejs_global_variables, name='nodejs_global_variabls'),
    path('nodejs_express/', views.nodejs_express, name='nodejs_express'),

    path('react_basics/', views.react_basics, name='react_basics'),
    path('react_and_django/', views.react_and_django, name='react_and_django'),
    path('react_examples/', views.react_examples, name='react_examples'),

    path('typescript_intro/', views.typescript_intro, name='typescript_intro'),

    path('typescript_reference/', views.typescript_reference, name='typescript_reference'),
]

WebDevProject/Ten/TenAppOne/models.py
from django.db import models

# Create your models here.

WebDevProject/Ten/TenAppOne/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.
def language_guides_home_view(request):
    return render(request, 'TenAppOne/language_guides_home.html')


def html_basics_view(request):
    return render(request, 'TenAppOne/html_basics.html')


def html_elements_reference_view(request):
    return render(request, 'TenAppOne/html_elements_reference.html')


def css_basics_view(request):
    return render(request, 'TenAppOne/css_basics.html')


def css_layouts_view(request):
    return render(request, 'TenAppOne/css_layouts.html')


def css_selectors_view(request):
    return render(request, 'TenAppOne/css_selectors.html')


def bootstrap_forms_view(request):
    return render(request, 'TenAppOne/bootstrap_forms.html')


def bootstrap_components_view(request):
    return render(request, 'TenAppOne/bootstrap_components.html')


def bootstrap_styling_view(request):
    return render(request, 'TenAppOne/bootstrap_styling.html')


@login_required()
def javascript_basics_view(request):
    return render(request, 'TenAppOne/javascript_basics.html')


@login_required()
def dom_basics_view(request):
    return render(request, 'TenAppOne/dom_basics.html')


@login_required()
def dom_reference_view(request):
    return render(request, 'TenAppOne/dom_reference.html')


@login_required()
def dom_events_reference_view(request):
    return render(request, 'TenAppOne/dom_events_reference.html')


@login_required()
def django_setup_view(request):
    return render(request, 'TenAppOne/django_setup.html')


@login_required()
def django_views_and_urls_view(request):
    return render(request, 'TenAppOne/django_views_and_urls.html')


@login_required()
def django_templates_view(request):
    context = {'ifchanged_dict': [1, 2, 1, 2, 2]}
    return render(request, 'TenAppOne/django_templates.html', context)


@login_required()
def django_static_files_view(request):
    return render(request, 'TenAppOne/django_static_files.html')


@login_required()
def django_models_view(request):
    return render(request, 'TenAppOne/django_models.html')


@login_required()
def django_admin_interface_view(request):
    return render(request, 'TenAppOne/django_admin_interface.html')


@login_required()
def django_creating_sample_data_view(request):
    return render(request, 'TenAppOne/django_creating_sample_data.html')


@login_required()
def django_model_queries_view(request):
    return render(request, 'TenAppOne/django_model_queries.html')


@login_required()
def django_mtv_paradigm_view(request):
    test_list = [1, 2, 3, 4]
    return render(request, 'TenAppOne/django_mtv_paradigm.html', context={'test_one': test_list})


@login_required()
def django_forms_view(request):
    return render(request, 'TenAppOne/django_forms.html')


@login_required()
def django_form_validation_view(request):
    return render(request, 'TenAppOne/django_form_validation.html')


@login_required()
def django_model_forms_view(request):
    return render(request, 'TenAppOne/django_model_forms.html')


@login_required()
def django_relative_urls_view(request):
    return render(request, 'TenAppOne/django_relative_urls.html')


@login_required()
def django_users_view(request):
    return render(request, 'TenAppOne/django_users.html')


@login_required()
def django_user_login_logout_view(request):
    return render(request, 'TenAppOne/django_user_login_logout.html')


@login_required()
def django_ecryption_and_validation_view(request):
    return render(request, 'TenAppOne/django_encryption_and_validation.html')


@login_required()
def django_deployment_view(request):
    return render(request, 'TenAppOne/django_deployment.html')


@login_required()
def django_cbvs_view(request):
    return render(request, 'TenAppOne/django_class_based_views.html')


def git_basics_view(request):
    return render(request, 'TenAppOne/git_basics.html')


def git_advanced_view(request):
    return render(request, 'TenAppOne/git_advanced.html')


def python_view(request):
    return render(request, 'TenAppOne/python.html')


@login_required()
def jquery_basics_view(request):
    return render(request, 'TenAppOne/jquery_basics.html')


def sql_basics_view(request):
    return render(request, 'TenAppOne/sql_basics.html')


def vim_basics_view(request):
    return render(request, 'TenAppOne/vim_basics.html')


def regex_reference_view(request):
    return render(request, 'TenAppOne/regex_reference.html')


@login_required()
def interview_prep_view(request):
    return render(request, 'TenAppOne/interview_prep.html')


@login_required()
def nodejs_intro_and_install(request):
    return render(request, 'TenAppOne/nodejs_intro_and_install.html')


# @login_required()
# def nodejs_global_variables(request):
#     return render(request, 'TenAppOne/nodejs_global_variables.html')


@login_required()
def nodejs_express(request):
    return render(request, 'TenAppOne/nodejs_express.html')


@login_required()
def react_and_django(request):
    return render(request, 'TenAppOne/react_and_django.html')


@login_required()
def react_basics(request):
    return render(request, 'TenAppOne/react_basics.html')


@login_required()
def react_examples(request):
    return render(request, 'TenAppOne/react_examples.html')


@login_required()
def typescript_intro(request):
    return render(request, 'TenAppOne/typescript_intro_and_install.html')


@login_required()
def typescript_reference(request):
    return render(request, 'TenAppOne/typescript_reference.html')

WebDevProject/Ten/templates/tenappone/bootstrap_other.html
<!DOCTYPE html>
{% extends 'base_template_languageguides.html' %}

{% load static %}

{% block head_block %}
<title>Bootstrap - Other</title>
<link rel="stylesheet" href="{% static 'css/global_styling.css' %}">
<link rel="stylesheet" href="{% static 'css/effects_styling.css' %}">
{% endblock %}

{% block body_block %}
<h1>Bootstrap <span class="door">-</span> Other</h1>
<p>
    Work-in-progress.
    <br>
    Contains various features/utilities that are pulled from various Bootstrap chapters at random. To be expanded upon
    as new skills are added.
</p>
<h2>Spacing, Sizing, and Gutters</h2>
<a href="https://getbootstrap.com/docs/4.1/utilities/sizing/">https://getbootstrap.com/docs/4.1/utilities/sizing/</a>
<a href="https://getbootstrap.com/docs/4.0/utilities/spacing/">https://getbootstrap.com/docs/4.0/utilities/spacing/</a>
<a href="https://getbootstrap.com/docs/5.0/layout/gutters/">https://getbootstrap.com/docs/5.0/layout/gutters/</a>
<h2>Text - Alignment, wrapping, overflow, break, transform, size, weight/italics, height, decoration, etc..</h2>
<a href="https://getbootstrap.com/docs/5.3/utilities/text/">https://getbootstrap.com/docs/5.3/utilities/text/</a>
{% endblock %}

WebDevProject/Ten/templates/tenappone/django_mtv_paradigm.html
<!DOCTYPE html>
{% extends 'base_template_languageguides.html' %}

{% load static %}

{% block head_block %}
<title>Django - Model-Template-View Paradigm</title>
<link rel="stylesheet" href="{% static 'css/global_styling.css' %}">
<link rel="stylesheet" href="{% static 'css/effects_styling.css' %}">
{% endblock %}

{% block body_block %}
<a id="django_mtv_paradigm_anchor"><h1>Django <span class="door">-</span> Model-Template-View Paradigm</h1></a>
<div class="form-control">
    <p class="mb-1">
        Django operates on the Model Template View (MTV) Paradigm - a software pattern, similar to MVC (Model View
        Controller). The goal of which is to serve dynamic content to the user based off of the connection between the
        models, views, and templates.
    </p>
    <ul class="mb-3">
        <li>
            The <strong><u>view</u></strong> describes the data that gets presented to the user. It is responsible for
            rendering a page. It's not necessarily <em>how</em> the data looks but <em>which</em> data is presented. The
            view describes <em>which</em> data you see, not <em>how</em> you see it. In Django, the '<em>view</em>' is
            the Python callback function for a particular URL, because that callback function describes which data is
            presented. It normally delegates to a template.
        </li>
        <li>
            The <strong><u>template</u></strong> describes how the data is presented. It is a chunk of text that acts as
            formatting for representing data. A template helps to abstract the presentation of data from the data
            itself.
        </li>
        <li>
            The <strong><u>model</u></strong> is what stores the application's data.
        </li>
    </ul>
    <div class="form-control mb-2">
        <a id="mtv_vs_mvc_anchor"><h3>Differences between an MTV and MVC:</h3></a>
        <p class="mb-1">
            In the MTV framework, what we describe as our 'view' is what the MVC framework would refer to as a
            'controller' and what we describe as our 'template' is what MVC would describe as a 'view'. In MTV, our
            'controller' is the framework itself - it is responsible for sending the request to the appropriate view,
            according to the URL configuration.
        </p>
    </div>
    <div class="form-control mb-2">
        <a id="views_anchor"><h3>Views - Importing Models, Querying, and Passing Data to the Template</h3></a>
        <div class="form-control mb-2">
            <h6>Example models.py from example app named 'first_app':</h6>
            <img src="{% static 'media/images/examples/django_mtv.example_modelspy.png' %}"
                 alt="django_mtv.example_modelspy.png" class="mb-1">
        </div>
        <ol>
            <li>
                <p class="mb-1">
                    Before a model from the <em>models.py</em> file can be used, it first needs to be imported into the
                    <em>views.py</em> file.
                </p>
                <p class="mb-1">
                    In the example below, we importing models from the app named 'first_app':
                </p>
                <pre class="mb-1">
from first_app.models import Topic, Webpage, AccessRecord
</pre>
            </li>
            <li>
                <p class="mb-1">
                    Once imported, the model can now be queried for the desired data. We can filter, order, and
                    manipulate it as needed.
                </p>
                <p class="mb-1">
                    In the below example, we retrieve data from AccessRecord, reorder the items by the '<em>date</em>'
                    field, and assign it to a variable:
                </p>
                <pre>
webpages_list = AccessRecord.objects.order_by('date')
</pre>
            </li>
            <li>
                <p class="mb-1">
                    Once the data is ready, it can be passed from the view to the template, where the data will be
                    displayed. To pass this data to the template, we need to use the <em>render()</em> method's optional
                    <em>context</em> parameter. This parameter accepts a dictionary of key-value pairs, consisting of a
                    string name and the set of data to be sent.
                </p>
                <p class="mb-1">
                    In the below example, we create a dictionary into which we pass a key-value pair consisting of
                    "access_records" as the key name, and <u>webpages_list</u> as the value. Then we assign the this
                    dictionary to the <em>context</em> parameter. Optionally, add another key-value pair to the dict:
                    {'some_numbers': [3,1,4,1,5,9]}.
                </p>
                <pre>
date_dict = {'access_records': webpages_list, 'some_numbers': [3,1,4,1,5,9]}
return render(request, 'first_app/index.html', context=date_dict)
</pre>
            </li>
        </ol>
        <div class="form-control mb-1">
            <h6>Example views.py:</h6>
            <pre class="mb-0">
from django.shortcuts import render
from first_app.models import Topic, Webpage, AccessRecord

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records': webpages_list, 'some_numbers': [3,1,4,1,5,9]}
    return render(request, 'first_app/index.html', context=date_dict)
</pre>
        </div>
    </div>
    <div class="form-control mb-1">
        <a id="templates_access_display_data_anchor"><h3>Templates - Accessing and Displaying the Data</h3></a>
        <ul class="mb-1">
            <li>
                <p class="mb-1">
                    In order to access a particular set of data sent from the view, we need to know the name of the key
                    that was assigned to that set. Once known, the associated data can be displayed on the page by using
                    the template tag lookup syntax: <code>{{"{"}}{{"{"}} key {{"}"}}{{"}"}}</code>. This template tag
                    will print out the entire content of the data set at once.
                </p>
                <p class="mb-1">
                    Refer to this <a href="{% url 'tenappone:django_templates' %}#template_variables_anchor">section</a>
                    for additional template tag syntaxes. Two commonly used ones below:
                </p>
                <table class="table table-bordered mb-2">
                    <tr class="table-dark">
                        <th class="col-1 text-center">Tag</th>
                        <th class="col-5">Description</th>
                        <th class="col-5">Syntax & Example Usage</th>
                    </tr>
                    <tr>
                        <th class="text-center">if</th>
                        <td>
                            <p>
                                Specifies an <em>if</em> statement that evaluates a condition(s). <em>if</em> statements
                                must be terminated with an <em>endif</em> tag. The <em>elif</em> and <em>else</em> are
                                optional. There's no limit on the number of <em>elif</em> tags or conditions per
                                <em>if</em> and <em>elif</em> tag.
                            </p>
                            <p>
                                Operators:
                                <br>
                                ==, !=, <, <=, >, >=, and, or, in, is, is not, not in
                            </p>
                        </td>
                        <td>
                            <pre class="mb-0">{% verbatim %}
Syntax:
{% <mark>if</mark> <em>condition</em> %}
    ...
{% <mark>elif</mark> <em>condition_1</em> <em>logical_operator</em> <em>condition_2</em> %} # optional
    ...
{% <mark>else</mark> %} # optional
    ...
{% <mark>endif</mark> %}
{% endverbatim %}</pre>
                            <hr class="my-1">
                            <pre class="mb-0">{% verbatim %}
Example usage:
{% if <em>first_name == "John" and last_name == "Doe"</em> %}
    &lt;p&gt;John Doe? Who are you, really?&lt;/p&gt;
{% elif <em>id < 10</em> %}
    &lt;p&gt;Welcome, founder.&lt;/p&gt;
{% else %}
    &lt;p&gt;Welcome, user.&lt;/p&gt;
{% endif %}
{% endverbatim %}</pre>
                        </td>
                    </tr>
                    <tr>
                        <th class="text-center">for</th>
                        <td>
                            <p>Iterates through a collection of items.</p>
                            <p>
                                For-loop variables (not covered here):
                                <br>
                                counter, counter0, first, last, parentloop, revcounter, revcounter()
                                <br>
                                (Refer to the template tag section for examples of usage)
                            </p>
                        </td>
                        <td>
                            <pre class="mb-0">{% verbatim %}
Syntax:
{% for <em>item_name</em> in <em>collection_object</em> %}
    {{ <em>item_name</em> }}        # technically optional
    {{ forloop.counter0 }}          # optional
    {{ forloop.first }}             # optional
    {{ forloop.last }}              # optional
    {{ forloop.parentloop }}        # optional
    {{ forloop.revcounter }}        # optional
    {{ forloop.revcounter0 }}       # optional
{% endfor %}
{% endverbatim %}</pre>
                            <hr class="my-1">
                            <pre class="mb-0">{% verbatim for_tag %}
Example usage:
{% for <em>person</em> in <em>team_roster</em> %}
    &lt;p&gt;Name:{{ <em>person.last_name</em> }}, {{ <em>person.first_name</em> }}&lt;/p&gt;
{% endfor %}
{% endverbatim for_tag %}</pre>
                        </td>
                    </tr>
                </table>
                <p class="mb-1">
                    In the example below, we enable the the data set (<em>webpages_list</em>) to be displayed by
                    supplying the associated key (<em>access_records</em>) into the template tag.
                </p>
                <pre>{% verbatim example_one %}
&lt;body&gt;
    &lt;p&gt;
        {{ access_records }}
    &lt;/p&gt;
&lt;/body&gt;
{% endverbatim example_one %}</pre>
            </li>
            <li>
                <p class="mb-1">
                    If the data set is a collection-type variable, then it can be iterated through, instead of printing
                    the contents all at once. This is done using the <em>for</em> template tag. It can used to
                    dynamically generate HTML elements as well, so for each item in our variable, it can create new HTML
                    elements alongside it, provided that they are created inside of the <em>for</em>/<em>endfor</em>
                    template tags. Before a variable is accessed, it's recommended to check to see if it exists first.
                    This is where the <em>if</em> template tag is useful - if the supplied key doesn't exist or has no
                    data, an alternative set of code/scripts can be provided for it to run.
                </p>
                <p class="mb-1">
                    In the example below, we use the <em>if</em> template tag to check if a key with the name
                    <u>some_numbers</u> exists and checks if the associated value is empty. If false, then it will
                    output a <em>p</em> element with a message. If true, then it creates a <em>ul</em> element. Inside
                    of this element, the <em>for</em> template tag will be called. It will iterate through the contents
                    of the <u>some_numbers</u> list, creating a <em>li</em> element for each one and supplying it with
                    the current iteration's item.
                </p>
                <pre class="mb-0">{% verbatim example_two %}
&lt;body&gt;
    ...
    {% if some_numbers %}
        &lt;ul&gt;
            {% for number in some_numbers %}
                &lt;li&gt;Score #: {{ number }}&lt;/li&gt;
            {% endfor %}
        &lt;/ul&gt;
    {% else %}
        &lt;p&gt;
            You're seeing this because there's either no data for the
            supplied key, or the key-value pair does not exist.
        &lt;/p&gt;
    {% endif %}
&lt;/body&gt;
{% endverbatim example_two %}</pre>
            </li>
        </ul>
    </div>

    {% verbatim test_area %}
    <!--        <h1>TEST AREA</h1>-->
    <!--        {{ test_one }}-->
    <!--        {% for num in test_one %}-->
    <!--        <p>{{ num }}</p>-->
    <!--        {% endfor %}-->
    <!--        {% if test_two %}-->
    <!--        <p>included</p>-->
    <!--        {% else %}-->
    <!--        <p>not included</p>-->
    <!--        {% endif %}-->
    {% endverbatim test_area %}
</div>
{% endblock %}

{% block chapter_block %}
Django - MTV Paradigm
{% endblock %}

{% block glossary_block %}
<li>
    <a class="dropdown-item" href="#django_mtv_paradigm_anchor"><strong>Django - Model-Template-View Paradigm</strong></a>
</li>
<li>
    <a class="dropdown-item" href="#mtv_vs_mvc_anchor">
        Differences between an MTV and MVC
    </a>
</li>
<li>
    <a class="dropdown-item" href="#views_anchor">
        Views - Importing Models, Querying, and Passing Data to the Template
    </a>
</li>
<li>
    <a class="dropdown-item" href="#templates_access_display_data_anchor">
        Templates - Accessing and Displaying the Data
    </a>
</li>
{% endblock %}

WebDevProject/Ten/templates/tenappone/jquery_basics.html
<!DOCTYPE html>
{% extends 'base_template_languageguides.html' %}

{% load static %}

{% block head_block %}
<title>JQuery - Basics</title>
<link rel="stylesheet" href="{% static 'css/global_styling.css' %}">
<link rel="stylesheet" href="{% static 'css/effects_styling.css' %}">
{% endblock %}

{% block body_block %}
<a id="dom_basics_anchor"><h1>JQuery <span class="door">-</span> Basics</h1></a>
<div class="form-control mb-1">
    <pre class="mb-0">
var anchor_tags = $('a'); // retrieves all anchor tags
console.log(anchor_tags);

for(var i = 0; i < anchor_tags.length; i++){
    console.log(anchor_tags[i].textContent);
//    console.log(anchor_tags[i].text); // Same as textContent
}


console.log($('#hello_button').text()); // retrieves the text; text seems to retrieve a function though.
$('#hello_button').text("Aloha"); // Changes the button's text to say 'Aloha'
console.log($('#hello_button').text());


$('button').text("what"); // Changes every buttons' text to say 'what'
console.log($('#hello_button').textC);


$('button').eq(0).text("Hello"); // Selects the first element in the list and changes the text value to 'Hello'
$('button').eq(1).text("Bye"); // Selects the second element in the list and changes the text value to 'Bye'
$('button').eq(2).text("*waves*"); // Selects the third element in the list and changes the text value to '*waves*'


// EVENT LISTENERS
$('button').eq(0).click(function(){ // Adds an event listener to the element that performs an action when clicked
    console.log("HELLO!");
});

$('button').eq(1).click(function(){
    $(this).text("Clicked!"); // Using the 'this' keyword to select the current element
});

$('button').eq(1).dblclick(function(){ // performs an action when a double-click is performed on the element
    $(this).text("Bye!");
});

$('#wave_button').mouseover(function(){
    $(this).css("background-color","yellow"); // the css function allows changing the css properties via javascript
});

$('#wave_button').mouseout(function(){
    $(this).css("background-color","inherit"); // the 'inherit' value changes the color back to the default value
});

$('#hello_button').mouseover(function(){
    $(this).toggleClass('peepee_poopoo_class');
});

$('#bye_button').mouseover(function(){
    $(this).toggleClass('bingbing_bongbong_class');
});

$('#text_0').keypress(function(){
    console.log("event.which: " + event.which + "; event.key: " + event.key);
    $('label').eq(0).text("First name: (" + event.key + ")");
});

$('#text_1').on('keypress', function(){
    console.log("event.which: " + event.which);
}); // Alternate way of writing element.keypress()

$('table').find("td").eq(1).text("yakayaka") //find


$('#slideup_p').click(function(){
    console.log('hello');
    $(this).slideUp(5000);
});

$('#fadeout_p').click(function(){
    $(this).fadeOut(5000);
});

$('#hide_p').click(function(){
    $(this).hide(5000);
});
</pre>
</div>
{% endblock %}

{% block chapter_block %}
JQuery - Basics
{% endblock %}

{% block glossary_block %}
{% endblock %}

WebDevProject/Ten/templates/tenappone/linux_commands.html
<!DOCTYPE html>
{% extends 'base_template_languageguides.html' %}

{% block head_block %}
{% endblock %}

{% block body_block %}
<a href="https://ubuntu.com/tutorials/command-line-for-beginners#3-opening-a-terminal">https://ubuntu.com/tutorials/command-line-for-beginners#3-opening-a-terminal</a>
{% endblock %}

{% block chapter_block %}
{% endblock %}

{% block glossary_block %}
{% endblock %}

WebDevProject/Ten/templates/tenappone/virtualenvwrapper_basics.html
<!DOCTYPE html>
{% extends 'base_template_languageguides.html' %}

{% block head_block %}
{% endblock %}

{% block body_block %}
<a href="https://www.geeksforgeeks.org/using-mkvirtualenv-to-create-new-virtual-environment-python/">https://www.geeksforgeeks.org/using-mkvirtualenv-to-create-new-virtual-environment-python/</a>
{% endblock %}

{% block chapter_block %}
{% endblock %}

{% block glossary_block %}
{% endblock %}